In [1]:
import tensorflow as tf
import sys

In [2]:
print(f"wersja tensorflow: {tf.__version__}")
print(f"wersja pythona: {sys.version_info}")

wersja tensorflow: 2.11.1
wersja pythona: sys.version_info(major=3, minor=8, micro=20, releaselevel='final', serial=0)


In [3]:
#ładowanie danych ze zbioru mnist
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()

#normalizacja danych
x_train,x_test = x_train/255.0,x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
#prosty model sieci neuronowej
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'), #funkcja relu max(0,x)
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [5]:
predictions = model(x_train[:1]).numpy()
print(predictions)

[[-0.07362117 -0.17084382  0.1891613   0.20372008  0.29202974  0.27361506
  -0.20473278  0.7957712   0.6643673  -0.21800816]]


In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07350793, 0.06669771, 0.09560029, 0.09700229, 0.10595815,
 0.10402482, 0.06447527, 0.1753503 , 0.15375829, 0.06362499]],
 dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2922 - accuracy: 0.9151
Epoch 2/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1431 - accuracy: 0.9571
Epoch 3/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1064 - accuracy: 0.9681
Epoch 4/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0870 - accuracy: 0.9736
Epoch 5/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0754 - accuracy: 0.9764
Epoch 6/20
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0651 - accuracy: 0.9793
Epoch 7/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0565 - accuracy: 0.9816
Epoch 8/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0504 - accuracy: 0.9836
Epoch 9/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0464 - accuracy: 0.9846
Epoch 10/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.044

In [15]:
#ocena modelu
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0886 - accuracy: 0.9806 - 731ms/epoch - 2ms/step


[0.08857481926679611, 0.9805999994277954]

In [16]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.31352409e-14, 6.93805026e-14, 2.95206047e-11, 1.05149729e-05,
        1.36916982e-18, 2.54903152e-12, 8.50108460e-25, 9.99989510e-01,
        9.49706026e-13, 4.04902378e-09],
       [1.24960547e-15, 6.15271389e-10, 1.00000000e+00, 4.89119335e-12,
        1.21449612e-28, 6.30990471e-16, 7.00513056e-17, 1.90970443e-25,
        5.71325244e-11, 1.48149388e-23],
       [7.41730191e-13, 9.99871850e-01, 6.41220254e-07, 2.17042437e-08,
        1.48771028e-06, 1.96208330e-08, 1.40183385e-08, 5.19980713e-05,
        7.40502728e-05, 1.26095879e-11],
       [1.00000000e+00, 5.73581463e-17, 1.72539121e-08, 4.57273759e-13,
        1.49616967e-15, 1.04883813e-09, 3.72053255e-09, 8.82164675e-10,
        3.64743769e-16, 9.92736382e-09],
       [5.68097965e-11, 9.19667887e-21, 7.52243060e-11, 2.44509545e-13,
        9.99839902e-01, 6.53016738e-11, 2.25680988e-10, 5.59421210e-07,
        5.10305409e-11, 1.59476331e-04]], dtype=float32)>

In [18]:
import numpy as np

In [27]:
w1 = probability_model(x_test[:1])
np.argmax(w1)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[4.3135075e-14, 6.9380110e-14, 2.9520549e-11, 1.0514933e-05,
        1.3691698e-18, 2.5490315e-12, 8.5010195e-25, 9.9998951e-01,
        9.4970429e-13, 4.0490313e-09]], dtype=float32)>

In [22]:
y_test[:2]

array([7, 2], dtype=uint8)