In [4]:
print("to jest pierwsza komórka!")
a = 17

to jest pierwsza komórka!


In [5]:
print(a)

17


To jest pierwszy **Notebook** oparty na <span style="color:red; font-size:15pt">Jupyter Notebook</span>

In [19]:
sztuki = 9

In [20]:
cena = "101.5"

In [21]:
wartosc_calk = float(cena) * int(sztuki)

In [22]:
wartosc_calk

913.5

In [23]:
#narzędzie biblioteki NUMPY
import numpy as np

In [24]:
print(np.__version__)

1.24.4


In [25]:
lista = [54,543,531,8,2,-457,0,78,-98]
type(lista)

list

In [26]:
ar = np.array(lista)
ar

array([ 54, 543, 531, 8, 2, -457, 0, 78, -98])

In [27]:
type(ar)

numpy.ndarray

In [28]:
np.array([4,2,6,2])

array([4, 2, 6, 2])

In [29]:
ts = np.linspace(0.0,9.99,1000)
ts

array([0. , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
 0.99, 1. , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
 1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
 1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
 1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
 1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53,
 1.54, 1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64,
 1.65, 1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75,
 1.76, 1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86,
 1.87, 1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97,
 1.98, 1.99, 2. , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08,
 2.09, 2.1 , 2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19,
 2.2 , 2.21, 2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 ,
 2.31, 2.32, 2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41,
 2.42, 2.43, 2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.5 , 2.51, 2.52,
 2.53, 2.54, 2.55, 2.56, 2.57, 2.58, 2.59, 2.6 , 2.61, 2.62, 2.63,
 2.64, 2.65, 2.66, 2.67, 2.68, 2.69, 2.7 , 2.71, 2.72, 2.73, 2.74,
 2.75, 2.76, 2.77, 2.78, 2.79, 2.8 , 2.81, 2.82, 2.83, 2.84, 2.85,
 2.86, 2.87, 2.88, 2.89, 2.9 , 2.91, 2.92, 2.93, 2.94, 2.95, 2.96,
 2.97, 2.98, 2.99, 3. , 3.01, 3.02, 3.03, 3.04, 3.05, 3.06, 3.07,
 3.08, 3.09, 3.1 , 3.11, 3.12, 3.13, 3.14, 3.15, 3.16, 3.17, 3.18,
 3.19, 3.2 , 3.21, 3.22, 3.23, 3.24, 3.25, 3.26, 3.27, 3.28, 3.29,
 3.3 , 3.31, 3.32, 3.33, 3.34, 3.35, 3.36, 3.37, 3.38, 3.39, 3.4 ,
 3.41, 3.42, 3.43, 3.44, 3.45, 3.46, 3.47, 3.48, 3.49, 3.5 , 3.51,
 3.52, 3.53, 3.54, 3.55, 3.56, 3.57, 3.58, 3.59, 3.6 , 3.61, 3.62,
 3.63, 3.64, 3.65, 3.66, 3.67, 3.68, 3.69, 3.7 , 3.71, 3.72, 3.73,
 3.74, 3.75, 3.76, 3.77, 3.78, 3.79, 3.8 , 3.81, 3.82, 3.83, 3.84,
 3.85, 3.86, 3.87, 3.88, 3.89, 3.9 , 3.91, 3.92, 3.93, 3.94, 3.95,
 3.96, 3.97, 3.98, 3.99, 4. , 4.01, 4.02, 4.03, 4.04, 4.05, 4.06,
 4.07, 4.08, 4.09, 4.1 , 4.11, 4.12, 4.13, 4.14, 4.15, 4.16, 4.17,
 4.18, 4.19, 4.2 , 4.21, 4.22, 4.23, 4.24, 4.25, 4.26, 4.27, 4.28,
 4.29, 4.3 , 4.31, 4.32, 4.33, 4.34, 4.35, 4.36, 4.37, 4.38, 4.39,
 4.4 , 4.41, 4.42, 4.43, 4.44, 4.45, 4.46, 4.47, 4.48, 4.49, 4.5 ,
 4.51, 4.52, 4.53, 4.54, 4.55, 4.56, 4.57, 4.58, 4.59, 4.6 , 4.61,
 4.62, 4.63, 4.64, 4.65, 4.66, 4.67, 4.68, 4.69, 4.7 , 4.71, 4.72,
 4.73, 4.74, 4.75, 4.76, 4.77, 4.78, 4.79, 4.8 , 4.81, 4.82, 4.83,
 4.84, 4.85, 4.86, 4.87, 4.88, 4.89, 4.9 , 4.91, 4.92, 4.93, 4.94,
 4.95, 4.96, 4.97, 4.98, 4.99, 5. , 5.01, 5.02, 5.03, 5.04, 5.05,
 5.06, 5.07, 5.08, 5.09, 5.1 , 5.11, 5.12, 5.13, 5.14, 5.15, 5.16,
 5.17, 5.18, 5.19, 5.2 , 5.21, 5.22, 5.23, 5.24, 5.25, 5.26, 5.27,
 5.28, 5.29, 5.3 , 5.31, 5.32, 5.33, 5.34, 5.35, 5.36, 5.37, 5.38,
 5.39, 5.4 , 5.41, 5.42, 5.43, 5.44, 5.45, 5.46, 5.47, 5.48, 5.49,
 5.5 , 5.51, 5.52, 5.53, 5.54, 5.55, 5.56, 5.57, 5.58, 5.59, 5.6 ,
 5.61, 5.62, 5.63, 5.64, 5.65, 5.66, 5.67, 5.68, 5.69, 5.7 , 5.71,
 5.72, 5.73, 5.74, 5.75, 5.76, 5.77, 5.78, 5.79, 5.8 , 5.81, 5.82,
 5.83, 5.84, 5.85, 5.86, 5.87, 5.88, 5.89, 5.9 , 5.91, 5.92, 5.93,
 5.94, 5.95, 5.96, 5.97, 5.98, 5.99, 6. , 6.01, 6.02, 6.03, 6.04,
 6.05, 6.06, 6.07, 6.08, 6.09, 6.1 , 6.11, 6.12, 6.13, 6.14, 6.15,
 6.16, 6.17, 6.18, 6.19, 6.2 , 6.21, 6.22, 6.23, 6.24, 6.25, 6.26,
 6.27, 6.28, 6.29, 6.3 , 6.31, 6.32, 6.33, 6.34, 6.35, 6.36, 6.37,
 6.38, 6.39, 6.4 , 6.41, 6.42, 6.43, 6.44, 6.45, 6.46, 6.47, 6.48,
 6.49, 6.5 , 6.51, 6.52, 6.53, 6.54, 6.55, 6.56,

In [30]:
%%time
68*ts

CPU times: user 584 µs, sys: 0 ns, total: 584 µs
Wall time: 644 µs


array([ 0. , 0.68, 1.36, 2.04, 2.72, 3.4 , 4.08, 4.76,
 5.44, 6.12, 6.8 , 7.48, 8.16, 8.84, 9.52, 10.2 ,
 10.88, 11.56, 12.24, 12.92, 13.6 , 14.28, 14.96, 15.64,
 16.32, 17. , 17.68, 18.36, 19.04, 19.72, 20.4 , 21.08,
 21.76, 22.44, 23.12, 23.8 , 24.48, 25.16, 25.84, 26.52,
 27.2 , 27.88, 28.56, 29.24, 29.92, 30.6 , 31.28, 31.96,
 32.64, 33.32, 34. , 34.68, 35.36, 36.04, 36.72, 37.4 ,
 38.08, 38.76, 39.44, 40.12, 40.8 , 41.48, 42.16, 42.84,
 43.52, 44.2 , 44.88, 45.56, 46.24, 46.92, 47.6 , 48.28,
 48.96, 49.64, 50.32, 51. , 51.68, 52.36, 53.04, 53.72,
 54.4 , 55.08, 55.76, 56.44, 57.12, 57.8 , 58.48, 59.16,
 59.84, 60.52, 61.2 , 61.88, 62.56, 63.24, 63.92, 64.6 ,
 65.28, 65.96, 66.64, 67.32, 68. , 68.68, 69.36, 70.04,
 70.72, 71.4 , 72.08, 72.76, 73.44, 74.12, 74.8 , 75.48,
 76.16, 76.84, 77.52, 78.2 , 78.88, 79.56, 80.24, 80.92,
 81.6 , 82.28, 82.96, 83.64, 84.32, 85. , 85.68, 86.36,
 87.04, 87.72, 88.4 , 89.08, 89.76, 90.44, 91.12, 91.8 ,
 92.48, 93.16, 93.84, 94.52, 95.2 , 95.88, 96.56, 97.24,
 97.92, 98.6 , 99.28, 99.96, 100.64, 101.32, 102. , 102.68,
 103.36, 104.04, 104.72, 105.4 , 106.08, 106.76, 107.44, 108.12,
 108.8 , 109.48, 110.16, 110.84, 111.52, 112.2 , 112.88, 113.56,
 114.24, 114.92, 115.6 , 116.28, 116.96, 117.64, 118.32, 119. ,
 119.68, 120.36, 121.04, 121.72, 122.4 , 123.08, 123.76, 124.44,
 125.12, 125.8 , 126.48, 127.16, 127.84, 128.52, 129.2 , 129.88,
 130.56, 131.24, 131.92, 132.6 , 133.28, 133.96, 134.64, 135.32,
 136. , 136.68, 137.36, 138.04, 138.72, 139.4 , 140.08, 140.76,
 141.44, 142.12, 142.8 , 143.48, 144.16, 144.84, 145.52, 146.2 ,
 146.88, 147.56, 148.24, 148.92, 149.6 , 150.28, 150.96, 151.64,
 152.32, 153. , 153.68, 154.36, 155.04, 155.72, 156.4 , 157.08,
 157.76, 158.44, 159.12, 159.8 , 160.48, 161.16, 161.84, 162.52,
 163.2 , 163.88, 164.56, 165.24, 165.92, 166.6 , 167.28, 167.96,
 168.64, 169.32, 170. , 170.68, 171.36, 172.04, 172.72, 173.4 ,
 174.08, 174.76, 175.44, 176.12, 176.8 , 177.48, 178.16, 178.84,
 179.52, 180.2 , 180.88, 181.56, 182.24, 182.92, 183.6 , 184.28,
 184.96, 185.64, 186.32, 187. , 187.68, 188.36, 189.04, 189.72,
 190.4 , 191.08, 191.76, 192.44, 193.12, 193.8 , 194.48, 195.16,
 195.84, 196.52, 197.2 , 197.88, 198.56, 199.24, 199.92, 200.6 ,
 201.28, 201.96, 202.64, 203.32, 204. , 204.68, 205.36, 206.04,
 206.72, 207.4 , 208.08, 208.76, 209.44, 210.12, 210.8 , 211.48,
 212.16, 212.84, 213.52, 214.2 , 214.88, 215.56, 216.24, 216.92,
 217.6 , 218.28, 218.96, 219.64, 220.32, 221. , 221.68, 222.36,
 223.04, 223.72, 224.4 , 225.08, 225.76, 226.44, 227.12, 227.8 ,
 228.48, 229.16, 229.84, 230.52, 231.2 , 231.88, 232.56, 233.24,
 233.92, 234.6 , 235.28, 235.96, 236.64, 237.32, 238. , 238.68,
 239.36, 240.04, 240.72, 241.4 , 242.08, 242.76, 243.44, 244.12,
 244.8 , 245.48, 246.16, 246.84, 247.52, 248.2 , 248.88, 249.56,
 250.24, 250.92, 251.6 , 252.28, 252.96, 253.64, 254.32, 255. ,
 255.68, 256.36, 257.04, 257.72, 258.4 , 259.08, 259.76, 260.44,
 261.12, 261.8 , 262.48, 263.16, 263.84, 264.52, 265.2 , 265.88,
 266.56, 267.24, 267.92, 268.6 , 269.28, 269.96, 270.64, 271.32,
 272. , 272.68, 273.36, 274.04, 274.72, 275.4 , 276.08, 276.76,
 277.44, 278.12, 278.8 , 279.48, 280.16, 280.84, 281.52, 282.2 ,
 282.88, 283.56, 284.24, 284.92, 285.6 , 286.28, 286.96, 287.64,
 288.32, 289. , 289.68, 290.36, 291.04, 291.72, 292.4 , 293.08,
 293.76, 294.44, 295.12, 295.8 , 296.48, 297.16, 297.84, 298.52,
 299.2 , 299.88, 300.56, 301.24, 301.92, 302.6 , 303.28, 303.96,
 304.64, 305.32, 306. , 306.68, 307.36, 308.04, 308.72, 309.4 ,
 310.08, 310.76, 311.44, 312.12, 312.8 , 313.48, 314.16, 314.84,
 315.52, 316.2 , 316.88, 317.56, 318.24, 318.92, 319.6 , 320.28,
 320.96, 321.64, 322.32, 323. , 323.68, 324.36, 325.04, 325.72,
 326.4 , 327.08, 327.76, 328.44, 329.12, 329.8 , 330.48, 331.16,
 331.84, 332.52, 333.2 , 333.88, 334.56, 335.24, 335.92, 336.6 ,
 337.28, 337.96, 338.64, 339.32, 340. , 340.68, 341.36, 342.04,
 342.72, 343.4 , 344.08, 344.76, 345.44, 346.12, 346.8 , 347.48,
 348.16, 348.84, 

In [31]:
np.arange(16_000_000)

array([ 0, 1, 2, ..., 15999997, 15999998, 15999999])

In [32]:
w = np.array([[1,2,3],[6,3,56],[98,112,77]])
w

array([[ 1, 2, 3],
 [ 6, 3, 56],
 [ 98, 112, 77]])

In [33]:
zwlist = [[3,5,2],[55,2,7],[8,6,23]]
zwlist

[[3, 5, 2], [55, 2, 7], [8, 6, 23]]

In [34]:
zwlist[1]

[55, 2, 7]

In [35]:
zwlist[1][2]

7

In [38]:
w[0][1]

2

In [39]:
w[0,1]

2

In [40]:
w[w<5]

array([1, 2, 3, 3])

In [42]:
pc = (w>16)
w[pc]

array([ 56, 98, 112, 77])

In [43]:
lg = (w%2==0)
w[lg]

array([ 2, 6, 56, 98, 112])

In [44]:
sv = w[(w>2)&(w<=32)]
sv

array([3, 6, 3])

In [45]:
l1 = [5,2,3,7]
l2 = [45,6,2.56,7.89]

lw = l1+l2
lw

[5, 2, 3, 7, 45, 6, 2.56, 7.89]

In [46]:
npl1 = np.array(l1)
npl2 = np.array(l2)

npl = npl1 + npl2

In [47]:
npl

array([50. , 8. , 5.56, 14.89])

In [48]:
nplcon = np.concatenate((npl1,npl2))
nplcon

array([ 5. , 2. , 3. , 7. , 45. , 6. , 2.56, 7.89])